const STORE='npoc_ops_v1_rebuilt_state';
const SETTINGS='npoc_ops_v1_rebuilt_settings';
const SESSION='npoc_ops_v1_rebuilt_session';
const ACCESS_CODE='npoc2026';
const DEFAULT_ADMINS=[
 {name:'Andrew',role:'Lead Admin',department:'Super Admin',active:true,email:''},
 {name:'Teece',role:'Assistant Lead Admin',department:'Super Admin',active:true,email:''},
 {name:'Ebi',role:'Class Admin',department:'Calls',active:true,email:''},
 {name:'Emmanuel',role:'Class Admin',department:'Calls',active:true,email:''},
 {name:'Tomi',role:'Class Admin',department:'Attendance',active:true,email:''},
 {name:'Gold',role:'Class Admin',department:'Attendance',active:true,email:''},
 {name:'Chinonso',role:'Class Admin',department:'Database',active:true,email:''},
 {name:'Success',role:'Class Admin',department:'Reports',active:true,email:''},
 {name:'Chinyere',role:'Class Admin',department:'Follow-up',active:true,email:''},
 {name:'Chinemeazu',role:'Class Admin',department:'SMS',active:true,email:''}
];
const STATUS=['Pending','Called - Interested','Called - Not Interested','No Response','Wrong Number','Registered','Follow Up Needed','Do Not Call','Duplicate','Completed'];
const MONTHS=['January 2026','February 2026','March 2026','April 2026','May 2026','June 2026','July 2026','August 2026','September 2026','October 2026','November 2026','December 2026'];
const MAY={month:'May 2026',parishioners:340,expected:120,actual:48,firstTimers:30,avgAttendance:10,graduates:12,classes:5,weeks:['May 3','May 10','May 17','May 24','May 31'],first:{physical:{expected:[7,19,10,6,7],actual:[6,6,6,1,6]},online:{expected:[6,0,9,7,9],actual:[2,0,0,0,2]}},second:{physical:{expected:[7,6,6,8,6],actual:[1,4,4,5,1]},online:{expected:[0,2,0,10,1],actual:[0,1,0,3,1]}},admin:[7,8,8,9,9]};
let state=load(STORE,{admins:DEFAULT_ADMINS,callList:[],attendance:[],adminAttendance:[],graduates:[],audit:[],sessions:[],expected:{May:MAY}});
let settings=load(SETTINGS,{backendUrl:'',apiKey:'',sheetId:'',allowedDomain:''});
let session=load(SESSION,null);
const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
function load(k,d){try{return JSON.parse(localStorage.getItem(k))||d}catch(e){return d}}
function save(){localStorage.setItem(STORE,JSON.stringify(state));}
function saveSettings(){localStorage.setItem(SETTINGS,JSON.stringify(settings));}
function saveSession(){localStorage.setItem(SESSION,JSON.stringify(session));}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function stamp(){return new Date().toLocaleString([], {year:'numeric',month:'short',day:'2-digit',hour:'2-digit',minute:'2-digit'})}
function iso(){return new Date().toISOString()}
function log(action,details=''){state.audit.unshift({time:iso(),user:session?.name||'System',admin:session?.admin||'',role:session?.role||'',action,details});state.audit=state.audit.slice(0,700);save();renderAudit();}
function activeAdmins(){return state.admins.filter(a=>a.active)}
function isLead(){return ['super','lead','assistant'].includes(session?.role)}
function cleanPhone(v){let s=String(v||'').replace(/\D/g,''); if(!s)return ''; if(s.startsWith('234'))return s; if(s.startsWith('0'))return '234'+s.slice(1); if(s.length===10)return '234'+s; return s.startsWith('234')?s:'234'+s.slice(-10)}
function monthKey(v){return (v||$('#monthSelect')?.value||'May 2026').split(' ')[0]}
function sameMonth(date,monthText){if(!date)return false; const d=new Date(date); return d.toLocaleString('en-US',{month:'long'})===monthKey(monthText)}
function today(){return new Date().toISOString().slice(0,10)}
function unique(arr){return [...new Set(arr.filter(Boolean))]}
function studentMap(){const m={}; state.callList.forEach(r=>{if(r.phone){m[r.phone]={name:r.name||'',phone:r.phone,email:r.email||'',source:'Call List'}}}); state.attendance.forEach(r=>{if(!r.phone)return; m[r.phone]=m[r.phone]||{name:r.name||'',phone:r.phone,email:'',source:'Attendance'}; if(r.name)m[r.phone].name=r.name;}); return m;}
function moduleCount(phone,module){return state.attendance.filter(r=>r.phone===phone&&r.module===module).length}
function studentRows(){const map=studentMap(); return Object.values(map).map(s=>{const m1=moduleCount(s.phone,'Module 1'),m2=moduleCount(s.phone,'Module 2'),att=state.attendance.filter(a=>a.phone===s.phone).sort((a,b)=>new Date(a.date)-new Date(b.date)); const grad=state.graduates.some(g=>g.phone===s.phone); let status='Yet to take Module 1'; if(m1>0&&m2===0)status='Yet to take Module 2'; if(m1>0&&m2>0)status='Eligible for Graduation'; if(grad)status='Graduated'; return {...s,m1,m2,status,first:att[0]?.date||'',last:att[att.length-1]?.date||''}});}
function mayDefaults(){ if(state.callList.length||state.attendance.length)return; const names=['Ayo Blessing','Faith Daniel','Joy Samuel','David Mark','Sarah James','Grace Paul','Tolu Ade','Mary John','Peter Isaac','Ruth Emmanuel','Daniel Ebi','Esther Gold']; const admins=activeAdmins().map(a=>a.name); state.callList=Array.from({length:34},(_,i)=>({id:'CL'+(i+1),name:names[i%names.length]+' '+(i+1),rawPhone:'08000000'+String(i+1).padStart(3,'0'),phone:cleanPhone('08000000'+String(i+1).padStart(3,'0')),email:'',assignedAdmin:admins[i%admins.length],status:'Pending',notes:'',registered:i%3===0,updated:stamp()})); save();}
function setLogoFallback(){ $$('.brand-img').forEach(img=>{img.addEventListener('error',()=>img.src=window.HOTR_LOGO_DATA);});}
function init(){setLogoFallback(); mayDefaults(); fillSelects(); bindEvents(); if(session){showApp();} else {$('#loginScreen').classList.remove('hidden');$('#appShell').classList.add('hidden')} setDates(); renderAll(); setTimeout(()=>$('#preloader')?.remove(),300);}
function fillSelects(){ const adminOptions=activeAdmins().map(a=>`<option>${a.name}</option>`).join(''); ['#loginAdmin','#adminViewSelect','#aaAdmin'].forEach(id=>{if($(id))$(id).innerHTML=adminOptions}); ['#monthSelect','#reportMonth'].forEach(id=>{$(id).innerHTML=MONTHS.map(m=>`<option ${m==='May 2026'?'selected':''}>${m}</option>`).join('')}); $('#callStatusFilter').innerHTML='<option>All</option>'+STATUS.map(s=>`<option>${s}</option>`).join('');}
function setDates(){['#attDate','#aaDate'].forEach(id=>{if($(id)&&!$(id).value)$(id).value=today()});}
function bindEvents(){
 $('#loginForm').addEventListener('submit',e=>{e.preventDefault(); if($('#loginCode').value&&$('#loginCode').value!==ACCESS_CODE)return toast('Invalid demo access code'); session={name:$('#loginName').value.trim(),admin:$('#loginAdmin').value,role:$('#loginRole').value,loginAt:iso(),sid:'S'+Date.now()}; state.sessions.unshift({id:session.sid,name:session.name,admin:session.admin,role:session.role,loginAt:session.loginAt,logoutAt:''}); save(); saveSession(); showApp(); log('LOGIN','Signed into hub');});
 $('#logoutBtn').onclick=()=>{const s=state.sessions.find(x=>x.id===session?.sid); if(s)s.logoutAt=iso(); log('LOGOUT','Signed out'); session=null; localStorage.removeItem(SESSION); save(); $('#loginScreen').classList.remove('hidden');$('#appShell').classList.add('hidden')};
 $('#menuBtn').onclick=()=>openSide(true); $('#closeSidebar').onclick=()=>openSide(false); $('#sidebarBackdrop').onclick=()=>openSide(false);
 $$('.nav button').forEach(b=>b.onclick=()=>navTo(b.dataset.page));
 $('#fileInput').onchange=e=>handleFile(e.target.files[0]); const dz=$('#dropzone'); dz.ondragover=e=>{e.preventDefault();dz.classList.add('drag')}; dz.ondragleave=()=>dz.classList.remove('drag'); dz.ondrop=e=>{e.preventDefault();dz.classList.remove('drag');handleFile(e.dataTransfer.files[0])};
 $('#distributeBtn').onclick=()=>{distributeCalls(); renderAll(); toast('Calls distributed'); log('DISTRIBUTE_CALLS',`${state.callList.length} records distributed`)};
 $('#clearCallListBtn').onclick=()=>{if(confirm('Clear imported call list?')){state.callList=[];save();renderAll();log('CLEAR_CALL_LIST')}};
 $('#downloadTemplateBtn').onclick=downloadTemplate;
 $('#adminViewSelect').onchange=renderMyCalls; $('#callStatusFilter').onchange=renderMyCalls; $('#copyAdminLinkBtn').onclick=copyAdminLink;
 $('#attendanceForm').onsubmit=e=>{e.preventDefault(); recordAttendance();}; $('#cameraScanBtn').onclick=cameraScan;
 $('#studentFilter').onchange=renderStudents; $('#markGraduatedBtn').onclick=markGraduated;
 $('#adminAttendanceForm').onsubmit=e=>{e.preventDefault(); recordAdminAttendance();};
 $('#generateReportBtn').onclick=renderReports; $('#copyReportBtn').onclick=copyReport;
 $('#addAdminBtn').onclick=()=>{state.admins.push({name:'New Admin',role:'Ordinary Admin',department:'Calls',active:true,email:''}); save(); fillSelects(); renderAdminEditor();}; $('#saveAdminsBtn').onclick=saveAdminEditor;
 $('#settingsForm').onsubmit=e=>{e.preventDefault(); settings={backendUrl:$('#backendUrl').value,apiKey:$('#apiKey').value,sheetId:$('#sheetId').value,allowedDomain:$('#allowedDomain').value}; saveSettings(); toast('Settings saved'); log('SAVE_SETTINGS')}; $('#syncBtn').onclick=syncBackend;
 $('#clearAuditBtn').onclick=()=>{if(confirm('Clear local audit log?')){state.audit=[];save();renderAudit();}};
 $('#monthSelect').onchange=renderAll; $('#reportMonth').onchange=renderReports;
}
function openSide(v){$('#sidebar').classList.toggle('open',v);$('#sidebarBackdrop').classList.toggle('show',v)}
function showApp(){ $('#loginScreen').classList.add('hidden'); $('#appShell').classList.remove('hidden'); $('#currentUser').textContent=session.name||session.admin; $('#currentRole').textContent=roleLabel(session.role); $('#avatar').textContent=(session.name||session.admin||'A')[0].toUpperCase(); fillSelects(); renderAll();}
function roleLabel(r){return {super:'Super Admin',lead:'Lead Admin',assistant:'Assistant Lead Admin',class:'Class Admin',admin:'Ordinary Admin'}[r]||r}
function navTo(id){$$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===id)); $$('.page').forEach(p=>p.classList.toggle('active',p.id===id)); $('#pageTitle').textContent=$(`[data-page="${id}"]`)?.textContent||'NPOC Hub'; openSide(false); if(id==='reports')renderReports(); if(id==='audit')renderAudit();}
function parseRows(rows){const norm=s=>String(s||'').trim().toLowerCase(); const heads=rows[0]||[]; const find=keys=>heads.findIndex(h=>keys.some(k=>norm(h).includes(k))); const nameI=find(['name','full name','surname','firstname','first name']); const phoneI=find(['phone','mobile','telephone','number']); const emailI=find(['email','mail']); const genderI=find(['gender','sex']); return rows.slice(1).map((r,i)=>{const raw=r[phoneI]||''; const phone=cleanPhone(raw); return {id:'CL'+Date.now()+i,name:String(r[nameI]||'').trim()||`Parishioner ${i+1}`,rawPhone:String(raw||''),phone,email:String(r[emailI]||'').trim(),gender:String(r[genderI]||'').trim(),assignedAdmin:'',status:'Pending',notes:'',registered:false,updated:stamp()}}).filter(r=>r.phone);}
async function handleFile(file){if(!file)return; const data=await file.arrayBuffer(); let rows=[]; if(file.name.toLowerCase().endsWith('.csv')){const text=new TextDecoder().decode(data); rows=text.split(/\r?\n/).filter(Boolean).map(l=>l.split(','));}else{const wb=XLSX.read(data,{type:'array'}); let best=[]; wb.SheetNames.forEach(n=>{const arr=XLSX.utils.sheet_to_json(wb.Sheets[n],{header:1,defval:''}); const score=arr.slice(0,8).flat().join(' ').toLowerCase(); const has=/(phone|mobile|name|email)/.test(score); if(has&&arr.length>best.length)best=arr;}); rows=best.length?best:XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{header:1,defval:''});}
 const parsed=parseRows(rows); const seen=new Set(state.callList.map(r=>r.phone)); let added=0; parsed.forEach(r=>{if(!seen.has(r.phone)){state.callList.push(r);seen.add(r.phone);added++}}); distributeCalls(); save(); $('#importStatus').textContent=`Imported ${added} new record(s) from ${file.name}. Duplicate rows were ignored.`; log('IMPORT_CALL_LIST',`${file.name}: ${added} new`); renderAll();}
function distributeCalls(){const admins=activeAdmins().map(a=>a.name); if(!admins.length)return; state.callList.forEach((r,i)=>{if(!r.assignedAdmin)r.assignedAdmin=admins[i%admins.length];}); save();}
function renderAll(){fillSelects(); renderDashboard(); renderCallList(); renderMyCalls(); renderAttendance(); renderStudents(); renderAdminAttendance(); renderReports(); renderAdminEditor(); renderSettings(); renderAudit();}
function metrics(){const students=studentRows(), month=$('#monthSelect')?.value||'May 2026'; const attMonth=state.attendance.filter(a=>sameMonth(a.date,month)); const firstTimers=students.filter(s=>sameMonth(s.first,month)).length || MAY.firstTimers; const grads=state.graduates.filter(g=>sameMonth(g.date,month)).length || MAY.graduates; const actual=attMonth.length || MAY.actual; const expected=MAY.expected; const rate=expected?Math.round(actual/expected*100):0; return {parishioners:state.callList.length||MAY.parishioners,expected,actual,firstTimers,avg:Math.round(actual/(MAY.classes||1)),grads,rate,students};}
function renderDashboard(){const m=metrics(); $('#heroRate').textContent=m.rate+'%'; const cards=[['Parishioners',m.parishioners,'Cleaned call-list records'],['Expected',m.expected,'Active expected students'],['Attendance',m.actual,'Actual monthly records'],['First Timers',m.firstTimers,'First attendance this month'],['Graduates',m.grads,'Marked graduates'],['Average',m.avg,'Attendance per class'],['Active Admins',activeAdmins().length,'Enabled admins'],['Rate',m.rate+'%','Actual vs expected']]; $('#kpiGrid').innerHTML=cards.map(c=>`<div class="kpi-card"><span>${c[0]}</span><b>${c[1]}</b><small>${c[2]}</small></div>`).join(''); $('#actionQueue').innerHTML=actionItems().map(x=>`<div class="feed-item"><b>${x.title}</b><span>${x.text}</span><small>${x.meta}</small></div>`).join(''); $('#roleCards').innerHTML=[['Super Admin','Full control','Import, users, reports'],['Lead Admin','Leadership dashboard','All operational metrics'],['Class Admin','Class operations','Attendance and assigned calls'],['Ordinary Admin','Restricted view','Own call list only']].map(r=>`<div class="role-card"><span>${r[0]}</span><b>${r[1]}</b><small>${r[2]}</small></div>`).join(''); drawBar('expectedActualChart',['Physical','Online'],[{name:'Expected',data:[76,44],color:'#71bf44'},{name:'Actual',data:[40,8],color:'#2563eb'}]); drawBar('pipelineChart',['Yet M1','Yet M2','Eligible','Graduated'],[{name:'Students',data:[m.students.filter(s=>s.status==='Yet to take Module 1').length, m.students.filter(s=>s.status==='Yet to take Module 2').length, m.students.filter(s=>s.status==='Eligible for Graduation').length, m.students.filter(s=>s.status==='Graduated').length],color:'#71bf44'}]);}
function actionItems(){const pending=state.callList.filter(r=>r.status==='Pending').length; const elig=studentRows().filter(s=>s.status==='Eligible for Graduation').length; const noMode=state.attendance.filter(a=>!a.mode).length; return [{title:'Pending calls',text:`${pending} call(s) still pending follow-up.`,meta:'Saturday assignment'}, {title:'Graduation eligibility',text:`${elig} student(s) eligible for graduation.`,meta:'Module 1 + Module 2 completed'}, {title:'Attendance quality',text:`${noMode} attendance records without mode.`,meta:'Physical / Online validation'}];}
function renderCallList(){ $('#callCountLabel').textContent=`${state.callList.length} records`; $('#callListBody').innerHTML=state.callList.map((r,i)=>`<tr><td>${r.name}</td><td>${r.rawPhone||''}</td><td>${r.phone}</td><td>${r.email||''}</td><td>${r.assignedAdmin||''}</td><td>${badge(r.status)}</td><td>${r.notes||''}</td></tr>`).join('')||`<tr><td colspan="7">Upload a church call list to begin.</td></tr>`;}
function renderMyCalls(){const admin=$('#adminViewSelect').value||session?.admin; const status=$('#callStatusFilter').value; let rows=isLead()?state.callList:state.callList.filter(r=>r.assignedAdmin===session.admin); if(admin&&isLead())rows=rows.filter(r=>r.assignedAdmin===admin); if(status&&status!=='All')rows=rows.filter(r=>r.status===status); $('#myCallsBody').innerHTML=rows.map((r,i)=>`<tr><td>${r.name}</td><td>${r.phone}</td><td><select data-call-status="${r.id}">${STATUS.map(s=>`<option ${s===r.status?'selected':''}>${s}</option>`).join('')}</select></td><td><input data-call-note="${r.id}" value="${escapeHtml(r.notes||'')}" /></td><td>${r.registered?'Yes':'No'}</td><td>${r.updated||''}</td></tr>`).join('')||`<tr><td colspan="6">No assigned calls found.</td></tr>`; $$('[data-call-status]').forEach(el=>el.onchange=()=>updateCall(el.dataset.callStatus,{status:el.value})); $$('[data-call-note]').forEach(el=>el.onchange=()=>updateCall(el.dataset.callNote,{notes:el.value}));}
function updateCall(id,patch){const r=state.callList.find(x=>x.id===id); if(!r)return; Object.assign(r,patch,{updated:stamp()}); save(); log('UPDATE_CALL',`${r.name} - ${r.status}`); renderCallList(); renderMyCalls();}
function recordAttendance(){const phone=cleanPhone($('#attPhone').value); const known=studentMap()[phone]; const name=$('#attName').value.trim() || known?.name || 'Unnamed Student'; const date=$('#attDate').value; const module=$('#attModule').value; const mode=$('#attMode').value; const first=!state.attendance.some(a=>a.phone===phone); state.attendance.push({id:'AT'+Date.now(),phone,name,date,module,mode,registered:$('#regStatus').value,first,createdAt:iso(),by:session?.admin}); const cl=state.callList.find(r=>r.phone===phone); if(cl){cl.registered=true; if(!cl.name)cl.name=name} save(); log('RECORD_ATTENDANCE',`${name} ${module} ${mode}`); $('#attendanceForm').reset(); setDates(); renderAll(); toast('Attendance recorded');}
function cameraScan(){ if('BarcodeDetector' in window){toast('Camera scan supported. Production build can activate camera scanner. Paste QR payload for this demo.')}else toast('This browser does not support native QR scan. Paste the QR payload manually.');}
function renderAttendance(){const rows=state.attendance.slice().reverse(); $('#attendanceCount').textContent=`${rows.length} records`; $('#attendanceBody').innerHTML=rows.map(r=>`<tr><td>${r.date}</td><td>${r.name}</td><td>${r.phone}</td><td>${r.module}</td><td>${r.mode}</td><td>${r.first?'Yes':'No'}</td><td>${r.registered}</td></tr>`).join('')||`<tr><td colspan="7">No attendance recorded yet.</td></tr>`; const m=metrics(); $('#attendanceIntel').innerHTML=[['Module 1 records',state.attendance.filter(a=>a.module==='Module 1').length],['Module 2 records',state.attendance.filter(a=>a.module==='Module 2').length],['Physical',state.attendance.filter(a=>a.mode==='Physical').length],['Online',state.attendance.filter(a=>a.mode==='Online').length]].map(x=>`<div class="mini-card"><span>${x[0]}</span><b>${x[1]}</b></div>`).join(''); $('#recentAttendance').innerHTML=rows.slice(0,6).map(r=>`<div class="feed-item"><b>${r.name}</b><span>${r.module} · ${r.mode}</span><small>${r.date} · ${r.phone}</small></div>`).join('')||'<div class="feed-item">No recent attendance.</div>';}
function renderStudents(){const filter=$('#studentFilter')?.value||'All'; let rows=studentRows(); if(filter!=='All')rows=rows.filter(s=>s.status===filter); const all=studentRows(); const counts=[['Registered',all.length],['Yet to take Module 1',all.filter(s=>s.status==='Yet to take Module 1').length],['Yet to take Module 2',all.filter(s=>s.status==='Yet to take Module 2').length],['Eligible for Graduation',all.filter(s=>s.status==='Eligible for Graduation').length],['Graduated',all.filter(s=>s.status==='Graduated').length],['Attendance records',state.attendance.length]]; $('#progressCards').innerHTML=counts.map(x=>`<div class="kpi-card"><span>${x[0]}</span><b>${x[1]}</b></div>`).join(''); $('#studentBody').innerHTML=rows.map(s=>`<tr><td>${s.name}</td><td>${s.phone}</td><td>${s.m1?badge('Completed','ok'):badge('Pending','warn')}</td><td>${s.m2?badge('Completed','ok'):badge('Pending','warn')}</td><td>${badge(s.status,s.status==='Graduated'?'ok':s.status.includes('Eligible')?'info':'warn')}</td><td>${s.first||''}</td><td>${s.last||''}</td></tr>`).join('')||'<tr><td colspan="7">No student record yet.</td></tr>';}
function markGraduated(){let n=0; studentRows().filter(s=>s.status==='Eligible for Graduation').forEach(s=>{state.graduates.push({phone:s.phone,name:s.name,date:today(),by:session?.admin}); n++}); save(); log('MARK_GRADUATES',`${n} students`); renderAll(); toast(`${n} eligible student(s) marked graduated`);}
function recordAdminAttendance(){state.adminAttendance.push({id:'AA'+Date.now(),admin:$('#aaAdmin').value,mode:$('#aaMode').value,date:$('#aaDate').value,duty:$('#aaDuty').value,by:session?.admin,time:iso()}); save(); log('ADMIN_CHECKIN',`${$('#aaAdmin').value} ${$('#aaMode').value}`); renderAdminAttendance(); renderDashboard(); toast('Admin attendance recorded');}
function renderAdminAttendance(){const rows=state.adminAttendance.slice().reverse(); $('#adminAttendanceBody').innerHTML=rows.map(r=>`<tr><td>${r.date}</td><td>${r.admin}</td><td>${r.mode}</td><td>${r.duty}</td><td>${r.by||''}</td><td>${new Date(r.time).toLocaleTimeString()}</td></tr>`).join('')||'<tr><td colspan="6">No admin attendance recorded.</td></tr>'; const weeks=MAY.weeks; drawLine('adminTrendChart',weeks,[{name:'Admin attendance',data:MAY.admin,color:'#71bf44'}]);}
function renderReports(){const m=metrics(); const boxes=[['Total HOTR Parishioners',m.parishioners],['Total Expected Count',m.expected],['Total Attendance Count',m.actual],['First-Time Attendance',m.firstTimers],['Average Attendance',m.avg],['Graduates',m.grads],['Classes Held',MAY.classes],['Attendance Rate',m.rate+'%']]; $('#reportSummary').innerHTML=boxes.map(b=>`<div class="report-card"><span>${b[0]}</span><b>${b[1]}</b></div>`).join(''); drawLine('firstClassChart',MAY.weeks,[{name:'Expected Physical',data:MAY.first.physical.expected,color:'#71bf44'},{name:'Actual Physical',data:MAY.first.physical.actual,color:'#2563eb'}]); drawLine('secondClassChart',MAY.weeks,[{name:'Expected Physical',data:MAY.second.physical.expected,color:'#71bf44'},{name:'Actual Physical',data:MAY.second.physical.actual,color:'#2563eb'}]);}
function copyReport(){const m=metrics(); const text=`NPOC Monthly Report - ${$('#reportMonth').value}\nTotal Parishioners: ${m.parishioners}\nExpected Count: ${m.expected}\nAttendance Count: ${m.actual}\nFirst-Time Attendance: ${m.firstTimers}\nAverage Attendance: ${m.avg}\nGraduates: ${m.grads}\nAttendance Rate: ${m.rate}%`; navigator.clipboard?.writeText(text); toast('Report summary copied');}
function renderAdminEditor(){if(!$('#adminEditor'))return; $('#adminEditor').innerHTML=state.admins.map((a,i)=>`<div class="admin-row"><input data-admin-name="${i}" value="${escapeHtml(a.name)}"/><select data-admin-role="${i}"><option ${a.role==='Super Admin'?'selected':''}>Super Admin</option><option ${a.role==='Lead Admin'?'selected':''}>Lead Admin</option><option ${a.role==='Assistant Lead Admin'?'selected':''}>Assistant Lead Admin</option><option ${a.role==='Class Admin'?'selected':''}>Class Admin</option><option ${a.role==='Ordinary Admin'?'selected':''}>Ordinary Admin</option></select><input data-admin-dept="${i}" value="${escapeHtml(a.department||'')}"/><select data-admin-active="${i}"><option ${a.active?'selected':''}>Active</option><option ${!a.active?'selected':''}>Inactive</option></select><button class="btn btn-danger" data-remove-admin="${i}">Remove</button></div>`).join(''); $$('[data-remove-admin]').forEach(b=>b.onclick=()=>{state.admins.splice(+b.dataset.removeAdmin,1);save();fillSelects();renderAdminEditor();});}
function saveAdminEditor(){state.admins=state.admins.map((a,i)=>({name:$(`[data-admin-name="${i}"]`).value.trim(),role:$(`[data-admin-role="${i}"]`).value,department:$(`[data-admin-dept="${i}"]`).value,active:$(`[data-admin-active="${i}"]`).value==='Active',email:a.email||''})).filter(a=>a.name); save(); fillSelects(); renderAll(); log('SAVE_ADMINS','Admin list updated'); toast('Admins updated');}
function renderSettings(){if(!$('#backendUrl'))return; $('#backendUrl').value=settings.backendUrl||''; $('#apiKey').value=settings.apiKey||''; $('#sheetId').value=settings.sheetId||''; $('#allowedDomain').value=settings.allowedDomain||'';}
function renderAudit(){ $('#auditFeed').innerHTML=(state.audit||[]).slice(0,100).map(a=>`<div class="feed-item"><b>${a.action}</b><span>${a.details||''}</span><small>${new Date(a.time).toLocaleString()} · ${a.user} · ${a.role}</small></div>`).join('')||'<div class="feed-item">No audit activity yet.</div>'; $('#sessionFeed').innerHTML=(state.sessions||[]).slice(0,80).map(s=>`<div class="feed-item"><b>${s.name||s.admin}</b><span>${roleLabel(s.role)} · ${s.admin||''}</span><small>In: ${new Date(s.loginAt).toLocaleString()}${s.logoutAt?' · Out: '+new Date(s.logoutAt).toLocaleString():' · Active/No logout'}</small></div>`).join('')||'<div class="feed-item">No sessions yet.</div>';}
function syncBackend(){ if(!settings.backendUrl)return toast('Add Apps Script Web App URL first.'); toast('Backend sync started'); log('SYNC_BACKEND','Demo sync called'); fetch(settings.backendUrl,{method:'POST',body:JSON.stringify({apiKey:settings.apiKey,action:'sync',payload:state})}).then(r=>r.json()).then(j=>toast('Backend sync completed')).catch(()=>toast('Could not reach backend. Check deployment URL/CORS.'));}
function copyAdminLink(){const admin=$('#adminViewSelect').value; const url=location.origin+location.pathname+'?admin='+encodeURIComponent(admin); navigator.clipboard?.writeText(url); toast('Admin link copied');}
function downloadTemplate(){const rows=[['Full Name','Phone Number','Email','Gender'],['John Doe','08012345678','john@example.com','Male']]; const csv=rows.map(r=>r.join(',')).join('\n'); download('npoc-call-list-template.csv',csv,'text/csv');}
function download(name,content,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function badge(text,type=''){return `<span class="badge ${type==='ok'?'ok':type==='warn'?'warn':type==='bad'?'bad':type==='info'?'info':''}">${text||''}</span>`}
function escapeHtml(s){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function drawBar(id,labels,series){const c=$('#'+id); if(!c)return; const ctx=c.getContext('2d'),w=c.width=c.clientWidth*devicePixelRatio,h=c.height=c.clientHeight*devicePixelRatio; ctx.scale(devicePixelRatio,devicePixelRatio); const W=c.clientWidth,H=c.clientHeight; ctx.clearRect(0,0,W,H); const pad=36,max=Math.max(1,...series.flatMap(s=>s.data)); ctx.strokeStyle='#e6eee0'; ctx.lineWidth=1; for(let i=0;i<4;i++){const y=pad+(H-pad*1.8)*i/3;ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(W-12,y);ctx.stroke();} const group=(W-pad-24)/labels.length,bw=Math.min(32,group/(series.length+1)); labels.forEach((l,i)=>{ctx.fillStyle='#66735f';ctx.font='12px Inter, sans-serif';ctx.textAlign='center';ctx.fillText(l,pad+group*i+group/2,H-10); series.forEach((s,j)=>{const val=s.data[i]||0, x=pad+group*i+group/2-bw*series.length/2+j*bw, bh=(H-pad*2)*(val/max), y=H-pad-bh; const g=ctx.createLinearGradient(0,y,0,H-pad);g.addColorStop(0,s.color);g.addColorStop(1,'#d7efcb'); ctx.fillStyle=g; roundRect(ctx,x,y,bw*.72,bh,8); ctx.fill(); ctx.fillStyle='#1f2f1d';ctx.font='bold 11px Inter';ctx.fillText(val,x+bw*.36,y-5);});});}
function drawLine(id,labels,series){const c=$('#'+id); if(!c)return; const ctx=c.getContext('2d'),ratio=devicePixelRatio||1,w=c.width=c.clientWidth*ratio,h=c.height=c.clientHeight*ratio; ctx.scale(ratio,ratio); const W=c.clientWidth,H=c.clientHeight,pad=34; ctx.clearRect(0,0,W,H); const max=Math.max(1,...series.flatMap(s=>s.data)); ctx.strokeStyle='#e6eee0'; for(let i=0;i<4;i++){let y=pad+(H-pad*2)*i/3;ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(W-12,y);ctx.stroke()} labels.forEach((l,i)=>{const x=pad+(W-pad-24)*i/(labels.length-1||1);ctx.fillStyle='#66735f';ctx.font='11px Inter';ctx.textAlign='center';ctx.fillText(l,x,H-9)}); series.forEach(s=>{ctx.strokeStyle=s.color;ctx.lineWidth=3;ctx.beginPath();s.data.forEach((v,i)=>{const x=pad+(W-pad-24)*i/(s.data.length-1||1),y=H-pad-(H-pad*2)*(v/max); if(i)ctx.lineTo(x,y);else ctx.moveTo(x,y)});ctx.stroke();s.data.forEach((v,i)=>{const x=pad+(W-pad-24)*i/(s.data.length-1||1),y=H-pad-(H-pad*2)*(v/max);ctx.fillStyle=s.color;ctx.beginPath();ctx.arc(x,y,4,0,Math.PI*2);ctx.fill();ctx.fillStyle='#1f2f1d';ctx.font='bold 11px Inter';ctx.fillText(v,x,y-9)})});}
function roundRect(ctx,x,y,w,h,r){r=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
window.addEventListener('resize',()=>setTimeout(()=>{renderDashboard();renderReports();renderAdminAttendance()},100));
init();
