/**
 * NPOC Operations Hub Backend Engine — V1.1 Backend Production Draft
 * Google Apps Script Web App backend for the NPOC Operations Hub front-end.
 *
 * Deploy as Web App:
 *  - Execute as: Me
 *  - Who has access: Anyone within your organisation OR Anyone with link (if needed)
 *  - Set Script Properties:
 *      API_KEY = a long random string
 *      FRONTEND_ORIGIN = your GitHub Pages/Netlify URL, optional
 *      FROM_NAME = Rock Foundation School
 *
 * Core production safeguards:
 *  - API key verification
 *  - Google account email capture where available
 *  - Role validation from Users sheet
 *  - LockService around writes
 *  - Audit logs for every mutation
 *  - Duplicate prevention by cleaned 234 phone number
 *  - Attendance validation and graduation eligibility
 *  - Queued Gmail sending with status, timestamps, and retry tracking
 */

const VERSION = '1.1.0-backend';
const TZ = 'Africa/Lagos';

const SHEETS = {
  SETTINGS: 'Settings',
  USERS: 'Users',
  ADMINS: 'Admins',
  CALL_LIST: 'Call_List',
  STUDENTS: 'Students',
  ATTENDANCE: 'Attendance',
  ADMIN_ATTENDANCE: 'Admin_Attendance',
  TASKS: 'Admin_Tasks',
  FACULTY: 'Faculty_Schedule',
  EMAIL_QUEUE: 'Email_Queue',
  GRADUATES: 'Graduates',
  REPORTS: 'Monthly_Reports',
  AUDIT: 'Audit_Log',
  SESSIONS: 'Sessions'
};

const HEADERS = {
  [SHEETS.SETTINGS]: ['Key','Value','Notes','Updated At'],
  [SHEETS.USERS]: ['Email','Display Name','Admin Name','Role','Status','Last Login','Last Logout','Created At'],
  [SHEETS.ADMINS]: ['Admin Name','Email','Role','Department','Status','Phone','Created At'],
  [SHEETS.CALL_LIST]: ['ID','Batch','Date Received','Full Name','Phone Raw','Phone Clean','Email','Gender','Assigned Admin','Call Status','Call Notes','Follow Up Date','Registered','First Timer','Created At','Updated At','Updated By'],
  [SHEETS.STUDENTS]: ['Student ID','Full Name','Phone Clean','Email','Gender','Source','Registration Date','Preferred Mode','Current Module','Status','First Attendance','Last Attendance','Module 1 Count','Module 2 Count','Attendance Count','Eligible To Graduate','Graduated','Updated At'],
  [SHEETS.ATTENDANCE]: ['Attendance ID','Timestamp','Class Date','Full Name','Phone Clean','Module','Attendance Mode','Registration Status','Is First Attendance','Recorded By','Source','Notes'],
  [SHEETS.ADMIN_ATTENDANCE]: ['ID','Timestamp','Class Date','Admin Name','Attendance Mode','Status','Recorded By','Notes'],
  [SHEETS.TASKS]: ['Task ID','Task Date','Task Title','Task Description','Assigned Admin','Priority','Due Date','Status','Completed Date','Score','Proof Link','Reviewer Comment','Created By','Updated At'],
  [SHEETS.FACULTY]: ['Class Date','Module','Faculty Name','Topic','Class Time','Venue','Mode','Status','Notes','Updated At','Updated By'],
  [SHEETS.EMAIL_QUEUE]: ['Email ID','Type','Recipient Name','Phone Clean','Email','Subject','Body','Status','Queued At','Sent At','Retry Count','Last Error','Queued By'],
  [SHEETS.GRADUATES]: ['Graduate ID','Graduation Date','Full Name','Phone Clean','Module 1 Count','Module 2 Count','Approved By','Notes'],
  [SHEETS.REPORTS]: ['Month','Year','Parishioners','Expected','Actual','First Timers','Average Attendance','Graduates','Physical','Online','Attendance Rate','Generated At','Generated By'],
  [SHEETS.AUDIT]: ['Timestamp','Actor Email','Actor Name','Role','Action','Entity','Entity ID','Details','IP/Client'],
  [SHEETS.SESSIONS]: ['Session ID','Email','Display Name','Role','Login At','Logout At','Status','Client']
};

const ROLES = {
  SUPER: 'Super Admin',
  LEAD: 'Lead Admin',
  ASSISTANT: 'Assistant Lead Admin',
  CLASS: 'Class Admin',
  ADMIN: 'Ordinary Admin'
};

const ROLE_LEVEL = {
  'Super Admin': 100,
  'Lead Admin': 80,
  'Assistant Lead Admin': 70,
  'Class Admin': 50,
  'Ordinary Admin': 20
};

const EMAIL_TEMPLATES = {
  FIRST_TIMER: {
    subject: 'Welcome to House on the Rock Lagos — NPOC Invitation',
    body: `Dear {{Name}},

Welcome again to House on the Rock (HOTR), Lagos. We were excited to see you in church for the first time and like our Pastor mentioned, we would like to see you again. We are even more excited that you intend to join the House on the Rock.

To kick-start your integration into the HOTR family, we invite you to the New Parishioners Orientation Class (NPOC).

This class holds on Sundays at Class 1.21 first floor of the church building from 7:45 am to 8:45 am.

The class is divided into 2 modules (Module 1 and Module 2) over two weeks. You are required to attend the two classes over two consecutive Sundays.

The New Parishioners’ Orientation Class (NPOC) is deliberately designed to enable you to know the House on the Rock better.

These two classes highlight the commitment of House on the Rock to:
- Treat the infallible Word of God with much dedication, ministering to your needs.
- Minister to your God ordained destiny.
- Assist you through the Word of God and covenant relationships to become all that God has called you to be and do.

Finally, the course also provides you with an overview of the vision, mission and core values of House on the Rock. You get to learn about the spread of House on the Rock in Nigeria, the importance of joining a Church In The Home (CITH) centre and the various opportunities to serve in House on the Rock.

For more information about this course and others, please call the Church Office (234-1-4614120).

Regards,
Rock Foundation School`
  },
  SECOND_TIMER: {
    subject: 'NPOC Module 2 Invitation — Complete Your Programme',
    body: `Dear {{Name}},

Once again you are most welcome to House on The Rock (Home for all).

Thank you for attending the first module of the New Parishioners Orientation Class.

We invite you to complete the Programme by attending Module 2 class after which you will successfully graduate from the programme.

Please find below the class details.

Date: {{Date}}
Time: 7:45am
Venue: Class 1.21 - The Rock Cathedral, Lekki, Lagos

We look forward to welcoming you to class.

Kind regards,
Teece Ogbu-Nnachi
Lead Admin (NPOC)`
  }
};

function doGet(e) {
  return jsonResponse({ ok: true, version: VERSION, message: 'NPOC backend is running.' });
}

function doPost(e) {
  try {
    const body = parseBody_(e);
    verifyApiKey_(body);
    const action = body.action;
    const payload = body.payload || {};
    const actor = resolveActor_(body);

    if (action !== 'login') requireSession_(body, actor);

    const routes = {
      setup: () => setup(),
      login: () => login_(payload, actor, e),
      logout: () => logout_(payload, actor),
      bootstrap: () => bootstrap_(actor),
      importCallList: () => importCallList_(payload, actor),
      distributeCalls: () => distributeCalls_(payload, actor),
      updateCallOutcome: () => updateCallOutcome_(payload, actor),
      recordAttendance: () => recordAttendance_(payload, actor),
      recordAdminAttendance: () => recordAdminAttendance_(payload, actor),
      saveTask: () => saveTask_(payload, actor),
      saveFacultySchedule: () => saveFacultySchedule_(payload, actor),
      queueEmail: () => queueEmail_(payload, actor),
      sendQueuedEmails: () => sendQueuedEmails_(payload, actor),
      approveGraduates: () => approveGraduates_(payload, actor),
      monthlyReport: () => monthlyReport_(payload, actor),
      auditLog: () => auditLog_(payload, actor)
    };

    if (!routes[action]) throw new Error('Unknown action: ' + action);
    return jsonResponse({ ok: true, action, data: routes[action]() });
  } catch (err) {
    return jsonResponse({ ok: false, error: String(err && err.message ? err.message : err) });
  }
}

function setup() {
  const ss = SpreadsheetApp.getActive();
  Object.keys(HEADERS).forEach(name => ensureSheet_(name, HEADERS[name]));
  seedDefaults_();
  return { created: Object.keys(HEADERS), version: VERSION };
}

function login_(payload, actor, e) {
  const email = (payload.email || Session.getActiveUser().getEmail() || '').toLowerCase().trim();
  const displayName = payload.displayName || payload.name || email || 'Admin';
  const accessCode = payload.accessCode || '';
  const demoCode = prop_('DEMO_ACCESS_CODE') || 'npoc2026';

  let user = email ? findUserByEmail_(email) : null;
  if (!user && accessCode !== demoCode) throw new Error('Access denied. User is not registered.');

  const role = user ? user.Role : normaliseRole_(payload.role || ROLES.ADMIN);
  const adminName = user ? user['Admin Name'] || displayName : payload.adminName || displayName;
  const sessionId = Utilities.getUuid();

  append_(SHEETS.SESSIONS, [sessionId, email, displayName, role, now_(), '', 'Active', JSON.stringify(payload.client || {})]);
  if (email) updateUserLogin_(email, true);
  audit_(actorFrom_(email, displayName, role), 'LOGIN', 'Session', sessionId, 'User logged in');
  return { sessionId, email, displayName, adminName, role, permissions: permissionsFor_(role) };
}

function logout_(payload, actor) {
  const sid = payload.sessionId || payload.token || '';
  if (!sid) return { loggedOut: false };
  const sh = sheet_(SHEETS.SESSIONS);
  const rows = objects_(SHEETS.SESSIONS);
  const idx = rows.findIndex(r => r['Session ID'] === sid);
  if (idx >= 0) {
    const row = idx + 2;
    setCell_(sh, row, 'Logout At', now_());
    setCell_(sh, row, 'Status', 'Logged Out');
  }
  if (actor.email) updateUserLogin_(actor.email, false);
  audit_(actor, 'LOGOUT', 'Session', sid, 'User logged out');
  return { loggedOut: true };
}

function bootstrap_(actor) {
  return {
    version: VERSION,
    actor,
    admins: objects_(SHEETS.ADMINS),
    settings: objects_(SHEETS.SETTINGS),
    facultySchedule: objects_(SHEETS.FACULTY),
    monthlyReport: monthlyReport_({ month: currentMonth_(), year: new Date().getFullYear() }, actor)
  };
}

function importCallList_(payload, actor) {
  requireRole_(actor, 70);
  const batch = payload.batch || ('Batch ' + formatDate_(new Date()));
  const records = payload.records || [];
  if (!Array.isArray(records)) throw new Error('records must be an array');

  const lock = LockService.getScriptLock();
  lock.waitLock(30000);
  try {
    const existing = new Set(objects_(SHEETS.CALL_LIST).map(r => String(r['Phone Clean'])));
    const admins = activeAdmins_();
    let added = 0, skipped = 0;
    records.forEach((r, i) => {
      const phone = cleanPhone_(r.phone || r.Phone || r['Phone Number'] || r['Phone Raw'] || '');
      if (!phone) { skipped++; return; }
      if (existing.has(phone)) { skipped++; return; }
      existing.add(phone);
      const admin = admins.length ? admins[added % admins.length]['Admin Name'] : '';
      append_(SHEETS.CALL_LIST, [
        id_('CL'), batch, payload.dateReceived || today_(), r.name || r.Name || r['Full Name'] || '',
        r.rawPhone || r.phone || r.Phone || '', phone, r.email || r.Email || '', r.gender || r.Gender || '',
        admin, 'Pending', '', '', 'No', 'No', now_(), now_(), actor.name || actor.email
      ]);
      added++;
    });
    audit_(actor, 'IMPORT_CALL_LIST', 'Call_List', batch, `${added} added, ${skipped} skipped`);
    return { added, skipped, batch };
  } finally {
    lock.releaseLock();
  }
}

function distributeCalls_(payload, actor) {
  requireRole_(actor, 70);
  const admins = activeAdmins_().map(a => a['Admin Name']);
  if (!admins.length) throw new Error('No active admins found');
  const sh = sheet_(SHEETS.CALL_LIST);
  const rows = objects_(SHEETS.CALL_LIST);
  let n = 0;
  rows.forEach((r, idx) => {
    if (!r['Assigned Admin'] || payload.redistribute) {
      setCell_(sh, idx + 2, 'Assigned Admin', admins[n % admins.length]);
      setCell_(sh, idx + 2, 'Updated At', now_());
      setCell_(sh, idx + 2, 'Updated By', actor.name || actor.email);
      n++;
    }
  });
  audit_(actor, 'DISTRIBUTE_CALLS', 'Call_List', '', `${n} records distributed`);
  return { distributed: n };
}

function updateCallOutcome_(payload, actor) {
  const id = payload.id;
  if (!id) throw new Error('Call ID is required');
  const rows = objects_(SHEETS.CALL_LIST);
  const idx = rows.findIndex(r => r.ID === id);
  if (idx < 0) throw new Error('Call record not found');
  const rec = rows[idx];
  if (ROLE_LEVEL[actor.role] < 70 && rec['Assigned Admin'] !== actor.adminName) throw new Error('You can only update your assigned calls.');
  const sh = sheet_(SHEETS.CALL_LIST);
  if (payload.status) setCell_(sh, idx + 2, 'Call Status', payload.status);
  if (payload.notes !== undefined) setCell_(sh, idx + 2, 'Call Notes', payload.notes);
  if (payload.followUpDate) setCell_(sh, idx + 2, 'Follow Up Date', payload.followUpDate);
  setCell_(sh, idx + 2, 'Updated At', now_());
  setCell_(sh, idx + 2, 'Updated By', actor.name || actor.email);
  audit_(actor, 'UPDATE_CALL_OUTCOME', 'Call_List', id, JSON.stringify(payload));
  return { updated: true };
}

function recordAttendance_(payload, actor) {
  requireRole_(actor, 50);
  const phone = cleanPhone_(payload.phone || payload.phoneClean || '');
  const module = normaliseModule_(payload.module);
  const mode = normaliseMode_(payload.mode || payload.attendanceMode);
  const classDate = payload.classDate || today_();
  if (!phone) throw new Error('Valid 234 phone number is required.');
  if (!module) throw new Error('Module 1 or Module 2 is required.');
  if (!mode) throw new Error('Physical or Online attendance mode is required.');

  const lock = LockService.getScriptLock();
  lock.waitLock(30000);
  try {
    const attendance = objects_(SHEETS.ATTENDANCE);
    const duplicate = attendance.some(a => String(a['Phone Clean']) === phone && String(a['Class Date']) === String(classDate) && String(a.Module) === module);
    if (duplicate) throw new Error('This student has already been marked for this module/date.');

    const student = upsertStudent_(payload, phone, actor);
    if (module === 'Module 2' && Number(student['Module 1 Count'] || 0) < 1) {
      // Soft validation: still allow, but audit it as a progression warning.
      audit_(actor, 'MODULE_2_BEFORE_MODULE_1_WARNING', 'Attendance', phone, 'Student recorded for Module 2 before Module 1 completion');
    }

    const firstAttendance = attendance.filter(a => String(a['Phone Clean']) === phone).length === 0;
    const id = id_('AT');
    append_(SHEETS.ATTENDANCE, [id, now_(), classDate, payload.name || student['Full Name'] || '', phone, module, mode, payload.registrationStatus || 'Registered', firstAttendance ? 'Yes' : 'No', actor.name || actor.email, payload.source || 'App', payload.notes || '']);
    refreshStudentProgress_(phone);

    if (firstAttendance) queueEmail_({ type: 'FIRST_TIMER', phone, name: payload.name || student['Full Name'], email: payload.email || student.Email }, actor);
    if (module === 'Module 1') queueEmail_({ type: 'SECOND_TIMER', phone, name: payload.name || student['Full Name'], email: payload.email || student.Email, nextClassDate: nextModule2Date_() }, actor);

    audit_(actor, 'RECORD_ATTENDANCE', 'Attendance', id, `${phone} ${module} ${mode}`);
    return { attendanceId: id, firstAttendance };
  } finally {
    lock.releaseLock();
  }
}

function recordAdminAttendance_(payload, actor) {
  const adminName = payload.adminName || actor.adminName || actor.name;
  const classDate = payload.classDate || today_();
  const mode = normaliseMode_(payload.mode || payload.attendanceMode);
  if (!adminName) throw new Error('Admin name is required.');
  if (!mode) throw new Error('Attendance mode is required.');
  const existing = objects_(SHEETS.ADMIN_ATTENDANCE).some(r => r['Admin Name'] === adminName && String(r['Class Date']) === String(classDate));
  if (existing) throw new Error('Admin attendance already recorded for this date.');
  const id = id_('AA');
  append_(SHEETS.ADMIN_ATTENDANCE, [id, now_(), classDate, adminName, mode, payload.status || 'Present', actor.name || actor.email, payload.notes || '']);
  audit_(actor, 'RECORD_ADMIN_ATTENDANCE', 'Admin_Attendance', id, `${adminName} ${mode}`);
  return { id };
}

function saveTask_(payload, actor) {
  requireRole_(actor, 50);
  const id = payload.taskId || id_('TK');
  const row = [id, payload.taskDate || today_(), payload.title || payload.taskTitle || '', payload.description || '', payload.assignedAdmin || '', payload.priority || 'Medium', payload.dueDate || '', payload.status || 'Pending', payload.completedDate || '', payload.score || '', payload.proofLink || '', payload.reviewerComment || '', actor.name || actor.email, now_()];
  upsertById_(SHEETS.TASKS, 'Task ID', id, row);
  audit_(actor, 'SAVE_TASK', 'Admin_Tasks', id, row[2]);
  return { taskId: id };
}

function saveFacultySchedule_(payload, actor) {
  requireRole_(actor, 70);
  const records = payload.records || [payload];
  records.forEach(r => {
    append_(SHEETS.FACULTY, [r.classDate || r.date || '', normaliseModule_(r.module) || r.module || '', r.facultyName || r.faculty || '', r.topic || '', r.classTime || '7:45am - 8:45am', r.venue || 'Class 1.21', r.mode || 'Hybrid', r.status || 'Scheduled', r.notes || '', now_(), actor.name || actor.email]);
  });
  audit_(actor, 'SAVE_FACULTY_SCHEDULE', 'Faculty_Schedule', '', `${records.length} records`);
  return { saved: records.length };
}

function queueEmail_(payload, actor) {
  const type = String(payload.type || '').toUpperCase();
  if (!EMAIL_TEMPLATES[type]) throw new Error('Unknown email type');
  const phone = cleanPhone_(payload.phone || '');
  const email = payload.email || findEmailByPhone_(phone);
  if (!email) {
    audit_(actor, 'EMAIL_NOT_QUEUED_NO_EMAIL', 'Email_Queue', phone, type);
    return { queued: false, reason: 'No email address found' };
  }
  const existing = objects_(SHEETS.EMAIL_QUEUE).some(q => q.Type === type && q.Email === email && ['Queued','Sent'].includes(q.Status));
  if (existing) return { queued: false, reason: 'Duplicate email prevented' };
  const tpl = EMAIL_TEMPLATES[type];
  const name = payload.name || findNameByPhone_(phone) || 'Friend';
  const body = tpl.body.replaceAll('{{Name}}', name).replaceAll('{{Date}}', payload.nextClassDate || nextModule2Date_() || 'Next Sunday');
  const id = id_('EM');
  append_(SHEETS.EMAIL_QUEUE, [id, type, name, phone, email, tpl.subject, body, 'Queued', now_(), '', 0, '', actor.name || actor.email || 'System']);
  audit_(actor, 'QUEUE_EMAIL', 'Email_Queue', id, `${type} to ${email}`);
  return { queued: true, emailId: id };
}

function sendQueuedEmails_(payload, actor) {
  requireRole_(actor, 70);
  const limit = Number(payload.limit || 20);
  const rows = objects_(SHEETS.EMAIL_QUEUE);
  const sh = sheet_(SHEETS.EMAIL_QUEUE);
  let sent = 0, failed = 0;
  for (let i = 0; i < rows.length && sent < limit; i++) {
    const r = rows[i];
    if (r.Status !== 'Queued' && r.Status !== 'Failed') continue;
    try {
      GmailApp.sendEmail(r.Email, r.Subject, r.Body, { name: prop_('FROM_NAME') || 'Rock Foundation School' });
      setCell_(sh, i + 2, 'Status', 'Sent');
      setCell_(sh, i + 2, 'Sent At', now_());
      setCell_(sh, i + 2, 'Last Error', '');
      sent++;
      audit_(actor, 'SEND_EMAIL', 'Email_Queue', r['Email ID'], r.Email);
    } catch (err) {
      setCell_(sh, i + 2, 'Status', 'Failed');
      setCell_(sh, i + 2, 'Retry Count', Number(r['Retry Count'] || 0) + 1);
      setCell_(sh, i + 2, 'Last Error', String(err.message || err));
      failed++;
    }
  }
  return { sent, failed };
}

function approveGraduates_(payload, actor) {
  requireRole_(actor, 70);
  const students = objects_(SHEETS.STUDENTS).filter(s => String(s['Eligible To Graduate']) === 'Yes' && String(s.Graduated) !== 'Yes');
  let approved = 0;
  students.forEach(s => {
    const id = id_('GR');
    append_(SHEETS.GRADUATES, [id, payload.graduationDate || today_(), s['Full Name'], s['Phone Clean'], s['Module 1 Count'], s['Module 2 Count'], actor.name || actor.email, payload.notes || '']);
    setStudentField_(s['Phone Clean'], 'Graduated', 'Yes');
    setStudentField_(s['Phone Clean'], 'Status', 'Graduated');
    approved++;
  });
  audit_(actor, 'APPROVE_GRADUATES', 'Graduates', '', `${approved} approved`);
  return { approved };
}

function monthlyReport_(payload, actor) {
  const month = payload.month || currentMonth_();
  const year = Number(payload.year || new Date().getFullYear());
  const attendance = objects_(SHEETS.ATTENDANCE).filter(r => isMonth_(r['Class Date'] || r.Timestamp, month, year));
  const callList = objects_(SHEETS.CALL_LIST);
  const students = objects_(SHEETS.STUDENTS);
  const grads = objects_(SHEETS.GRADUATES).filter(r => isMonth_(r['Graduation Date'], month, year));
  const firstTimers = attendance.filter(r => r['Is First Attendance'] === 'Yes').length;
  const physical = attendance.filter(r => r['Attendance Mode'] === 'Physical').length;
  const online = attendance.filter(r => r['Attendance Mode'] === 'Online').length;
  const expected = students.filter(s => String(s.Status || '').toLowerCase() !== 'graduated' && String(s.Status || '').toLowerCase() !== 'inactive').length;
  const actual = attendance.length;
  const classes = unique_(attendance.map(r => String(r['Class Date']))).length || Number(payload.classesHeld || 0) || 1;
  const report = {
    month, year,
    parishioners: unique_(callList.map(r => r['Phone Clean']).filter(Boolean)).length,
    expected,
    actual,
    firstTimers,
    averageAttendance: Math.round(actual / classes),
    graduates: grads.length,
    physical,
    online,
    attendanceRate: expected ? actual / expected : 0,
    firstClass: classSummary_('Module 1', attendance),
    secondClass: classSummary_('Module 2', attendance),
    adminAttendance: adminAttendanceSummary_(month, year)
  };
  return report;
}

function auditLog_(payload, actor) {
  requireRole_(actor, 70);
  return objects_(SHEETS.AUDIT).slice(-Number(payload.limit || 200)).reverse();
}

/* Helpers */
function parseBody_(e) { return e && e.postData && e.postData.contents ? JSON.parse(e.postData.contents) : {}; }
function jsonResponse(obj) { return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON); }
function verifyApiKey_(body) { const key = prop_('API_KEY'); if (key && body.apiKey !== key) throw new Error('Invalid API key.'); }
function prop_(k) { return PropertiesService.getScriptProperties().getProperty(k); }
function ss_() { return SpreadsheetApp.getActive(); }
function sheet_(name) { return ensureSheet_(name, HEADERS[name]); }
function ensureSheet_(name, headers) { const ss = ss_(); let sh = ss.getSheetByName(name); if (!sh) sh = ss.insertSheet(name); if (headers && sh.getLastRow() === 0) sh.appendRow(headers); if (headers && sh.getLastRow() >= 1 && sh.getRange(1,1,1,headers.length).getValues()[0].join('|') !== headers.join('|')) { sh.getRange(1,1,1,headers.length).setValues([headers]); } return sh; }
function objects_(name) { const sh = sheet_(name); const vals = sh.getDataRange().getValues(); if (vals.length < 2) return []; const headers = vals[0]; return vals.slice(1).filter(r => r.some(v => v !== '')).map(r => Object.fromEntries(headers.map((h,i) => [h, r[i]]))); }
function append_(name, row) { sheet_(name).appendRow(row); }
function colMap_(sh) { const headers = sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0]; return Object.fromEntries(headers.map((h,i)=>[h,i+1])); }
function setCell_(sh, row, header, value) { const col = colMap_(sh)[header]; if (!col) throw new Error('Header not found: ' + header); sh.getRange(row,col).setValue(value); }
function now_() { return Utilities.formatDate(new Date(), TZ, 'yyyy-MM-dd HH:mm:ss'); }
function today_() { return Utilities.formatDate(new Date(), TZ, 'yyyy-MM-dd'); }
function formatDate_(d) { return Utilities.formatDate(new Date(d), TZ, 'yyyy-MM-dd'); }
function currentMonth_() { return Utilities.formatDate(new Date(), TZ, 'MMMM'); }
function id_(prefix) { return prefix + '-' + Utilities.getUuid().slice(0,8).toUpperCase(); }
function cleanPhone_(v) { let s = String(v || '').replace(/[^0-9]/g,''); if (!s) return ''; if (s.length === 11 && s[0] === '0') return '234' + s.slice(1); if (s.length === 10) return '234' + s; if (s.startsWith('234') && s.length >= 13) return s.slice(0,13); return s; }
function normaliseRole_(r) { const x = String(r || '').toLowerCase(); if (x.includes('super')) return ROLES.SUPER; if (x.includes('assistant')) return ROLES.ASSISTANT; if (x.includes('lead')) return ROLES.LEAD; if (x.includes('class')) return ROLES.CLASS; return ROLES.ADMIN; }
function normaliseModule_(m) { const x = String(m || '').toLowerCase(); if (x.includes('1') || x.includes('first')) return 'Module 1'; if (x.includes('2') || x.includes('second')) return 'Module 2'; return ''; }
function normaliseMode_(m) { const x = String(m || '').toLowerCase(); if (x.includes('phys')) return 'Physical'; if (x.includes('online')) return 'Online'; return ''; }
function actorFrom_(email, name, role) { return { email, name, role, adminName: name }; }
function resolveActor_(body) { const token = body.sessionId || body.token || ''; const email = (body.email || Session.getActiveUser().getEmail() || '').toLowerCase().trim(); if (token) { const s = objects_(SHEETS.SESSIONS).find(r => r['Session ID'] === token && r.Status === 'Active'); if (s) return actorFrom_(s.Email, s['Display Name'], s.Role); } const u = email ? findUserByEmail_(email) : null; return actorFrom_(email, u ? u['Display Name'] : (body.displayName || 'Unknown'), u ? u.Role : ROLES.ADMIN); }
function requireSession_(body, actor) { if (!body.sessionId && !body.token && !actor.email) throw new Error('Active session required.'); }
function requireRole_(actor, min) { if ((ROLE_LEVEL[actor.role] || 0) < min) throw new Error('Insufficient permissions for this action.'); }
function permissionsFor_(role) { const lvl = ROLE_LEVEL[role] || 0; return { canImport: lvl>=70, canReport: lvl>=70, canManageUsers: lvl>=100, canRecordAttendance: lvl>=50, canUpdateOwnCalls: lvl>=20, canSendEmail: lvl>=70 }; }
function findUserByEmail_(email) { return objects_(SHEETS.USERS).find(u => String(u.Email).toLowerCase() === String(email).toLowerCase() && u.Status !== 'Inactive'); }
function updateUserLogin_(email, login) { const sh = sheet_(SHEETS.USERS); const rows = objects_(SHEETS.USERS); const idx = rows.findIndex(u => String(u.Email).toLowerCase() === email); if (idx >= 0) setCell_(sh, idx + 2, login ? 'Last Login' : 'Last Logout', now_()); }
function activeAdmins_() { return objects_(SHEETS.ADMINS).filter(a => String(a.Status || '').toLowerCase() !== 'inactive'); }
function unique_(arr) { return [...new Set(arr.filter(Boolean))]; }
function isMonth_(date, month, year) { if (!date) return false; const d = new Date(date); if (isNaN(d)) return false; return Utilities.formatDate(d,TZ,'MMMM') === month && Number(Utilities.formatDate(d,TZ,'yyyy')) === Number(year); }
function classSummary_(module, attendance) { const rows = attendance.filter(a => a.Module === module); return { total: rows.length, physical: rows.filter(a => a['Attendance Mode']==='Physical').length, online: rows.filter(a => a['Attendance Mode']==='Online').length }; }
function adminAttendanceSummary_(month, year) { const rows = objects_(SHEETS.ADMIN_ATTENDANCE).filter(r => isMonth_(r['Class Date'], month, year)); const names = unique_(rows.map(r => r['Admin Name'])); return names.map(name => ({ admin: name, count: rows.filter(r => r['Admin Name'] === name).length, physical: rows.filter(r => r['Admin Name'] === name && r['Attendance Mode'] === 'Physical').length, online: rows.filter(r => r['Admin Name'] === name && r['Attendance Mode'] === 'Online').length })); }
function upsertById_(sheetName, idHeader, id, row) { const sh = sheet_(sheetName); const rows = objects_(sheetName); const idx = rows.findIndex(r => r[idHeader] === id); if (idx >= 0) sh.getRange(idx + 2, 1, 1, row.length).setValues([row]); else append_(sheetName, row); }
function findEmailByPhone_(phone) { const s = objects_(SHEETS.STUDENTS).find(x=>x['Phone Clean']===phone); if (s && s.Email) return s.Email; const c = objects_(SHEETS.CALL_LIST).find(x=>x['Phone Clean']===phone); return c ? c.Email : ''; }
function findNameByPhone_(phone) { const s = objects_(SHEETS.STUDENTS).find(x=>x['Phone Clean']===phone); if (s && s['Full Name']) return s['Full Name']; const c = objects_(SHEETS.CALL_LIST).find(x=>x['Phone Clean']===phone); return c ? c['Full Name'] : ''; }
function nextModule2Date_() { const f = objects_(SHEETS.FACULTY).find(r => r.Module === 'Module 2' && r.Status !== 'Completed'); return f ? f['Class Date'] : ''; }
function upsertStudent_(payload, phone, actor) { const sh = sheet_(SHEETS.STUDENTS); const rows = objects_(SHEETS.STUDENTS); const idx = rows.findIndex(s => s['Phone Clean'] === phone); if (idx >= 0) return rows[idx]; const id = id_('ST'); const name = payload.name || findNameByPhone_(phone) || ''; const email = payload.email || findEmailByPhone_(phone) || ''; append_(SHEETS.STUDENTS, [id, name, phone, email, payload.gender || '', payload.source || 'Attendance', today_(), payload.preferredMode || '', 'Module 1', 'Active', '', '', 0, 0, 0, 'No', 'No', now_()]); audit_(actor, 'CREATE_STUDENT', 'Students', id, phone); return objects_(SHEETS.STUDENTS).find(s => s['Phone Clean'] === phone); }
function refreshStudentProgress_(phone) { const att = objects_(SHEETS.ATTENDANCE).filter(a => a['Phone Clean'] === phone); const m1 = att.filter(a => a.Module === 'Module 1').length; const m2 = att.filter(a => a.Module === 'Module 2').length; const first = att.length ? att.map(a=>new Date(a['Class Date'])).sort((a,b)=>a-b)[0] : ''; const last = att.length ? att.map(a=>new Date(a['Class Date'])).sort((a,b)=>b-a)[0] : ''; const status = m1 && m2 ? 'Eligible for Graduation' : m1 ? 'Yet to take Module 2' : 'Yet to take Module 1'; ['First Attendance','Last Attendance','Module 1 Count','Module 2 Count','Attendance Count','Eligible To Graduate','Status','Updated At'].forEach((field, i) => { const val = [first?formatDate_(first):'', last?formatDate_(last):'', m1, m2, att.length, (m1&&m2?'Yes':'No'), status, now_()][i]; setStudentField_(phone, field, val); }); }
function setStudentField_(phone, field, value) { const sh = sheet_(SHEETS.STUDENTS); const rows = objects_(SHEETS.STUDENTS); const idx = rows.findIndex(s => s['Phone Clean'] === phone); if (idx >= 0) setCell_(sh, idx + 2, field, value); }
function seedDefaults_() { const admins = objects_(SHEETS.ADMINS); if (!admins.length) ['Andrew','Teece','Ebi','Emmanuel','Tomi','Gold','Chinonso','Success','Chinyere','Chinemeazu'].forEach((name,i)=>append_(SHEETS.ADMINS,[name,'',i===0?ROLES.SUPER:ROLES.ADMIN,'NPOC','Active','',now_()])); if (!objects_(SHEETS.USERS).length) append_(SHEETS.USERS,['','Demo User','Andrew',ROLES.SUPER,'Active','','',now_()]); }
function audit_(actor, action, entity, entityId, details) { append_(SHEETS.AUDIT, [now_(), actor.email || '', actor.name || '', actor.role || '', action, entity, entityId || '', details || '', 'AppsScript']); }
